[tools]
"github:ast-grep/ast-grep" = "latest"
"github:jj-vcs/jj" = "latest"
"github:smallstep/cli" = { version = "latest", exe = "step" }
# "github:bgreenwell/lstr" = "latest"
# "github:boyter/scc" = "latest"
# "github:hetznercloud/cli" = { version = "1.49.0", exe = "hcloud" }
# "github:typst/typst" = "latest"
# deno = "latest"
# fnox = "latest"
# helm = "latest"
# kubectl = "latest"
# kustomize = "latest"
# pnpm = "latest"
# zellij = "latest"
age = "latest"
delta = "latest"
duckdb = "latest"
fd = "latest"
hyperfine = "latest"
jq = "latest"
lnav = "latest"
ruff = "latest"
shellcheck = "latest"
slsa-verifier = "latest"
sops = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
