[tools]
"ubi:ast-grep/ast-grep" = "latest"
"ubi:boyter/scc" = "latest"
"ubi:hetznercloud/cli" = { version = "1.49.0", exe = "hcloud" }
"ubi:smallstep/cli" = { version = "latest", exe = "step" }
gdu = "latest"
jq = "latest"
lazygit = "latest"
node = "latest"
python = "3.12"
ruff = "latest"
shellcheck = "latest"
usage = "latest"
uv = "latest"
helm = "latest"
kubectl = "latest"
delta = "latest"
zellij = "latest"
kustomize = "latest"
"ubi:typst/typst" = "latest"
sops = "latest"
age = "latest"
slsa-verifier = "latest"
pnpm = "latest"
"ubi:jj-vcs/jj" = "latest"
"ubi:bgreenwell/lstr" = "latest"
duckdb = "latest"
hyperfine = "latest"
fd = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
